# Food Environmental Impact
## ILV Datenvisualisierung und Visual Analytics
## Christina Köck
## Februar 2023
### Link to the Gitlab-Repo: https://gitlab.web.fh-kufstein.ac.at/christina.koeck/datenvisualisierung_und_visualanalytics

Die Visualisierungen werden in diesem Notebook erstellt. Designentscheidungen werden hier dokumentiert. Nach der Entwicklung wird der Code in eine streamlit-Anwendung für das Dashboarding übertragen.

Die Streamlit-Anwendung ist für interessierte Verbaucher mit leicht wissenschaftlichem Hintergrund gedacht. Die Informationen sollten für VerbraucherInnen verständlich sein, allerdings sind gewisse Kenntnisse zu den Nachhaltigkeitsparamtern vorausgesetzt. Besonders die Darstellung der Korrelation setzt Kenntnisse der Pearson-Korrelation voraus. Die Streamlit-Anwendung könnte auch im Unterricht verwendet werden, um Lernenden verschiedene Ernährungsformen näherzubringen. Die Anwendung ist so gestaltet, dass sie mit verschiedenen Fragen durch die Daten führt. Somit soll auf verschiedene Aspekte und Zusammenhänge hingewiesen werden. Die NutzerInnen können dabei selbst wählen, welche Lebenmittel dargestellt werden sollen.

### Libraries and data

In [5]:
import math as math
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import plotly.express as px

In [6]:
# Data are from:
# Hannah Ritchie and Max Roser (2022)
# "Environmental Impacts of Food Production".
# Published online at OurWorldInData.org. 'https://ourworldindata.org/environmental-impacts-of-food' [Online Resource]
# Data was retrieved in a shorter form from https://www.kaggle.com/datasets/selfvivek/environment-impact-of-food-production
df_food = pd.read_csv("Food_Production.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [7]:
df_food

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal),Eutrophying emissions per kilogram (gPO₄eq per kilogram),Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein),Freshwater withdrawals per 1000kcal (liters per 1000kcal),Freshwater withdrawals per 100g protein (liters per 100g protein),Freshwater withdrawals per kilogram (liters per kilogram),Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal),Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein),Land use per 1000kcal (m² per 1000kcal),Land use per kilogram (m² per kilogram),Land use per 100g protein (m² per 100g protein),Scarcity-weighted water use per kilogram (liters per kilogram),Scarcity-weighted water use per 100g protein (liters per 100g protein),Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,4.281357,11.23,8.638462,183.911552,371.076923,482.4,0.945482,1.907692,2.897446,7.60,5.846154,18786.2,14450.923080,7162.104461
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,9.514379,35.07,49.394366,609.983722,3166.760563,2248.4,1.207271,6.267606,0.759631,2.80,3.943662,49576.3,69825.774650,13449.891480
5,Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,4.754098,3.48,20.470588,80.737705,347.647059,59.1,0.628415,2.705882,1.202186,0.88,5.176471,2754.2,16201.176470,3762.568306
6,Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,0.9,0.708419,0.69,7.666667,NaN,NaN,0.0,1.355236,14.666667,1.858316,1.81,20.111111,0.0,NaN,NaN
7,Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,2.6,4.820513,16.92,NaN,176.666667,NaN,620.1,0.911681,NaN,0.581197,2.04,NaN,16438.6,NaN,4683.361823
8,Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,1.4,1.541311,5.41,NaN,62.022792,NaN,217.7,0.515670,NaN,0.521368,1.83,NaN,9493.3,NaN,2704.643875
9,Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,1.6,5.008798,17.08,7.977581,NaN,203.503036,435.7,0.524927,0.836058,4.565982,15.57,7.272303,22477.4,10498.552080,NaN
10,Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,0.8,2.173410,7.52,3.384338,NaN,178.487849,396.6,0.283237,0.441044,2.156069,7.46,3.357336,27948.2,12577.947790,NaN
11,Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,0.2,3.113821,19.15,11.726883,672.162602,2531.414574,4133.8,0.069919,0.263319,2.107317,12.96,7.936314,229889.8,140777.587300,37380.455280
12,Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,2.4,2.437931,14.14,5.401070,319.362069,707.524828,1852.3,0.556897,1.233766,1.570690,9.11,3.479756,61797.9,23605.003820,10654.810340
13,Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,1.0,NaN,1.06,NaN,NaN,NaN,27.8,NaN,NaN,NaN,0.66,NaN,955.6,NaN,NaN
14,Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,6.0,NaN,11.69,NaN,NaN,NaN,414.6,NaN,NaN,NaN,10.52,NaN,14888.2,NaN,NaN
16,Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,7.6,1.207014,10.67,NaN,0.723982,NaN,6.4,0.828054,NaN,0.273756,2.42,NaN,36.2,NaN,4.095023
17,Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,3.5,5.730769,50.66,NaN,114.015837,NaN,1007.9,0.407240,NaN,1.997738,17.66,NaN,36369.4,NaN,4114.185520
18,Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,3.7,2.170814,19.19,NaN,26.889140,NaN,237.7,0.426471,NaN,1.202489,10.63,NaN,10593.7,NaN,1198.382353
19,Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,6.0,4.214932,37.26,NaN,242.285068,NaN,2141.8,0.613122,NaN,2.976244,26.31,NaN,177480.2,NaN,20076.945700
20,Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,1.4,39.526316,7.51,68.272727,1946.315789,3361.818182,369.8,11.000000,19.000000,4.210526,0.80,7.272727,5335.7,48506.363640,28082.631580
21,Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,8.756757,3.24,24.923077,38.648649,110.000000,14.3,1.351351,3.846154,1.054054,0.39,3.000000,932.0,7169.230769,2518.918919
22,Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,4.351351,1.61,16.100000,76.756757,284.000000,28.4,1.162162,4.300000,0.891892,0.33,3.300000,929.2,9292.000000,2511.351351
23,Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,0.4,29.470588,5.01,45.545455,702.352941,1085.454545,119.4,3.000000,4.636364,3.235294,0.55,5.000000,8455.1,76864.545450,49735.882350
24,Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,0.5,NaN,2.27,NaN,NaN,NaN,102.5,NaN,NaN,NaN,0.38,NaN,4911.4,NaN,NaN
25,Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,0.3,7.000000,2.24,37.333333,258.437500,1378.333333,82.7,1.218750,6.500000,2.687500,0.86,14.333333,4662.7,77711.666670,14570.937500
26,Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,0.8,5.483333,3.29,36.555556,190.833333,1272.222222,114.5,1.433333,9.555556,3.216667,1.93,21.444444,661.9,7354.444444,1103.166667
27,Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,3.020833,1.45,48.333333,375.208333,6003.333333,180.1,0.895833,14.333333,1.312500,0.63,21.000000,12948.6,431620.000000,26976.250000
28,Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,1.1,10.736842,6.12,61.200000,736.140351,4196.000000,419.6,2.684211,15.300000,4.228070,2.41,24.100000,21162.1,211621.000000,37126.491230
29,Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,1.4,NaN,4.57,NaN,NaN,NaN,78.9,NaN,NaN,NaN,1.78,NaN,1149.3,NaN,NaN
30,Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,0.7,NaN,2.43,NaN,NaN,NaN,153.5,NaN,NaN,NaN,0.89,NaN,9533.1,NaN,NaN
31,Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,16.5,197.357143,110.52,138.150000,46.250000,32.375000,25.9,50.946429,35.662500,38.607143,21.62,27.025000,337.0,421.250000,601.785714
32,Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,18.7,16.843327,87.08,174.160000,104.564797,1081.200000,540.6,9.023211,93.300000,13.338491,68.96,137.920000,2879.2,5758.400000,556.905222
33,Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,59.6,110.406593,301.41,151.158475,531.575092,727.783350,1451.2,36.439560,49.889669,119.490842,326.21,163.595787,34732.5,17418.505520,12722.527470
34,Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,21.1,133.805861,365.29,185.050659,994.249084,1375.025329,2714.3,12.197802,16.869301,15.838828,43.24,21.904762,119805.2,60691.590680,43884.688640
35,Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,24.5,30.640379,97.13,48.540730,568.706625,900.949525,1802.8,12.529968,19.850075,116.659306,369.81,184.812594,141925.0,70927.036480,44771.293380
36,Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,7.2,31.958159,76.38,47.206428,751.380753,1109.888752,1795.8,5.150628,7.608158,7.263598,17.36,10.729295,66867.4,41327.194070,27977.991630
37,Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,6.1,26.324324,48.70,28.117783,356.756757,381.062356,660.0,5.335135,5.698614,6.605405,12.22,7.055427,14177.9,8185.854503,7663.729730
38,Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,2.8,17.750000,10.65,32.272727,1047.000000,1903.636364,628.2,5.250000,9.500000,14.916667,8.95,27.121212,19786.3,59958.484850,32977.166670
39,Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,21.2,25.418605,98.37,44.551630,1448.372093,2538.586957,5605.2,6.170543,10.815217,22.684755,87.79,39.759964,180850.6,81906.974640,46731.421190
40,Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,4.5,15.111111,21.76,19.610671,401.180556,520.638068,577.7,3.243056,4.208724,4.354167,6.27,5.650685,17982.7,16206.470800,12487.986110
41,Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,5.1,131.351955,235.12,103.100197,2062.178771,1618.636264,3691.3,7.614525,5.976759,4.698324,8.41,3.687788,41572.2,18229.423370,23224.692740
42,Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,11.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Short EDA

In [8]:
df_food.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 23 columns):
 #   Column                                                                   Non-Null Count  Dtype
---  ------                                                                   --------------  -----
 0   Food product                                                             43 non-null     object
 1   Land use change                                                          43 non-null     float64
 2   Animal Feed                                                              43 non-null     float64
 3   Farm                                                                     43 non-null     float64
 4   Processing                                                               43 non-null     float64
 5   Transport                                                                43 non-null     float64
 6   Packging                                                                 43 non-null     float64
 7   Retail                                                                   43 non-null     float64
 8   Total_emissions                                                          43 non-null     float64
 9   Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal)                 33 non-null     float64
 10  Eutrophying emissions per kilogram (gPO₄eq per kilogram)                 38 non-null     float64
 11  Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein)    27 non-null     float64
 12  Freshwater withdrawals per 1000kcal (liters per 1000kcal)                30 non-null     float64
 13  Freshwater withdrawals per 100g protein (liters per 100g protein)        26 non-null     float64
 14  Freshwater withdrawals per kilogram (liters per kilogram)                38 non-null     float64
 15  Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)             33 non-null     float64
 16  Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)     27 non-null     float64
 17  Land use per 1000kcal (m² per 1000kcal)                                  33 non-null     float64
 18  Land use per kilogram (m² per kilogram)                                  38 non-null     float64
 19  Land use per 100g protein (m² per 100g protein)                          27 non-null     float64
 20  Scarcity-weighted water use per kilogram (liters per kilogram)           38 non-null     float64
 21  Scarcity-weighted water use per 100g protein (liters per 100g protein)   26 non-null     float64
 22  Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)  30 non-null     float64
dtypes: float64(22), object(1)
memory usage: 7.9+ KB

In [9]:
df_food.describe()

,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal),Eutrophying emissions per kilogram (gPO₄eq per kilogram),Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein),Freshwater withdrawals per 1000kcal (liters per 1000kcal),Freshwater withdrawals per 100g protein (liters per 100g protein),Freshwater withdrawals per kilogram (liters per kilogram),Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal),Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein),Land use per 1000kcal (m² per 1000kcal),Land use per kilogram (m² per kilogram),Land use per 100g protein (m² per 100g protein),Scarcity-weighted water use per kilogram (liters per kilogram),Scarcity-weighted water use per 100g protein (liters per 100g protein),Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories)
count,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,43.000000,33.000000,38.000000,27.000000,30.000000,26.000000,38.000000,33.000000,27.000000,33.000000,38.000000,27.000000,38.000000,26.000000,30.000000
mean,1.260465,0.453488,3.469767,0.253488,0.195349,0.269767,0.069767,5.972093,27.181547,46.141316,52.771953,504.188977,1437.975324,932.605263,5.633943,13.524906,12.423165,29.264474,29.105042,36607.428947,59196.438503,17380.575408
std,3.357730,0.919200,7.083264,0.372475,0.158795,0.342633,0.110270,10.501753,46.445959,82.808808,52.033823,539.130695,1441.981970,1296.999186,10.613575,19.427462,28.348693,78.490074,49.307339,56891.283046,89928.189299,16232.080209
min,-2.100000,0.000000,0.100000,0.000000,0.000000,0.000000,0.000000,0.200000,0.708419,0.690000,3.384338,0.723982,32.375000,0.000000,0.069919,0.263319,0.273756,0.330000,3.000000,0.000000,421.250000,4.095023
25%,0.000000,0.000000,0.350000,0.000000,0.100000,0.100000,0.000000,0.850000,4.214932,3.752500,17.855335,106.927557,373.573281,105.500000,0.628415,4.027439,1.312500,1.112500,5.088235,3325.075000,11018.401008,2969.124983
50%,0.200000,0.000000,0.800000,0.100000,0.100000,0.100000,0.000000,1.600000,7.000000,11.460000,37.333333,338.059413,1083.327272,417.100000,1.351351,6.500000,2.976244,6.865000,7.936314,14533.050000,20917.213595,12605.256790
75%,0.800000,0.000000,2.200000,0.300000,0.200000,0.300000,0.150000,6.000000,26.324324,45.840000,55.297183,694.805356,1832.386339,1340.375000,5.335135,14.983333,6.605405,14.917500,23.002381,35960.175000,70651.721023,28056.471593
max,16.300000,2.900000,39.400000,1.300000,0.800000,1.600000,0.300000,59.600000,197.357143,365.290000,185.050659,2062.178771,6003.333333,5605.200000,50.946429,93.300000,119.490842,369.810000,184.812594,229889.800000,431620.000000,49735.882350

All data are numeric/float.

'Land use change' has negative values, all other columns have min 0 or above.
According to the [notebook Analysis,Visualization,Imputation -Food Production](https://www.kaggle.com/code/jamespauls/analysis-visualization-imputation-food-production#2.-Importing-Libraries-and-Datasets) this is the explanation: "Since the trees of nut crops sequester carbon dioxide, when they replace some grasslands this can actually result in an emission saving due to positive land use change."


'Freshwater withdrawals per 100g protein (liters per 100g protein)' and 'Scarcity-weighted water use per 100g protein (liters per 100g protein)' only have 26 non-null values of 43.

### Feature engineering
Code from the [notebook Analysis,Visualization,Imputation -Food Production](https://www.kaggle.com/code/jamespauls/analysis-visualization-imputation-food-production#2.-Importing-Libraries-and-Datasets)

In [10]:
# Creating a food category column which we will retain for all following sections of this analysis.
# Code from https://www.kaggle.com/code/jamespauls/analysis-visualization-imputation-food-production#2.-Importing-Libraries-and-Datasets

df_food["Category"] = df_food["Food product"] # creating a new column with the exact list of [Food_Products]

# Setting various lists for different types of [Food_Products]
Grains = ["Wheat & Rye (Bread)", "Maize (Meal)", "Oatmeal", "Barley (Beer)", "Rice"]
Nuts = ['Nuts', 'Groundnuts']
Vegetables = ["Potatoes", "Cassava", 'Other Pulses',"Peas",'Tomatoes', 'Onions & Leeks','Root Vegetables',"Brassicas",'Other Vegetables']
Fruits = ['Citrus Fruit', 'Bananas','Apples', 'Berries & Grapes', 'Other Fruit']
Sugars = ['Cane Sugar', 'Beet Sugar',]
Oils = ['Soybean Oil', 'Palm Oil', 'Sunflower Oil', 'Rapeseed Oil', 'Olive Oil']
Dairy = ['Milk', 'Cheese']
Animal_Prod = ['Beef (beef herd)', 'Beef (dairy herd)','Lamb & Mutton', 'Pig Meat', 'Poultry Meat', 'Fish (farmed)', 'Shrimps (farmed)']
Other = ["Coffee", "Dark Chocolate", "Wine"]
Plant_Dairy = ["Soymilk", "Tofu"]
Egg_Prod = ['Eggs']

# Replacing all [Food_Products] in the newly developed column with their respective food [Category]
for i in df_food["Category"]:
    if i in Grains:
        df_food["Category"].replace([i], "Grains", inplace=True)
    elif i in Nuts:
        df_food["Category"].replace([i], "Nuts", inplace=True)
    elif i in Vegetables:
        df_food["Category"].replace([i], "Vegetables", inplace=True)
    elif i in Fruits:
        df_food["Category"].replace([i], "Fruits", inplace=True)
    elif i in Sugars:
        df_food["Category"].replace([i], "Sugar", inplace=True)
    elif i in Oils:
        df_food["Category"].replace([i], "Oils", inplace=True)
    elif i in Dairy:
        df_food["Category"].replace([i], "Dairy", inplace=True)
    elif i in Animal_Prod:
        df_food["Category"].replace([i], "Animal_Prod", inplace=True)
    elif i in Other:
        df_food["Category"].replace([i], "Other", inplace=True)
    elif i in Plant_Dairy:
        df_food["Category"].replace([i], "Plant_Dairy", inplace=True)
    elif i in Egg_Prod:
        df_food["Category"].replace([i], "Egg_Prod", inplace=True)

Own code
Define category if further processing in the kitchen before consumption is needed [Further processing needed]:
Consumption is only possible with extensive heat treatment.

Options:

no

yes

The options are chosen to be strings and not encoded for easier usage in the visualisations.

In [11]:
df_food['Further processing needed'] = df_food["Food product"]
processing = ['Wheat & Rye (Bread)',
    'Maize (Meal)',
    'Barley (Beer)',
    'Rice',
    'Potatoes',
    'Cassava',
    'Other Pulses',
    'Peas',
    'Coffee',
    'Beef (beef herd)',
    'Beef (dairy herd)',
    'Lamb & Mutton',
    'Pig Meat',
    'Poultry Meat',
    'Eggs',
    'Fish (farmed)',
    'Shrimps (farmed)']

for food in df_food['Further processing needed']:
    if food in processing:
        df_food["Further processing needed"].replace([food], "yes", inplace=True)
    else:
        df_food["Further processing needed"].replace([food], "no", inplace=True)

In [12]:
df_food

,Food product,Land use change,Animal Feed,Farm,Processing,Transport,Packging,Retail,Total_emissions,Eutrophying emissions per 1000kcal (gPO₄eq per 1000kcal),Eutrophying emissions per kilogram (gPO₄eq per kilogram),Eutrophying emissions per 100g protein (gPO₄eq per 100 grams protein),Freshwater withdrawals per 1000kcal (liters per 1000kcal),Freshwater withdrawals per 100g protein (liters per 100g protein),Freshwater withdrawals per kilogram (liters per kilogram),Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal),Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein),Land use per 1000kcal (m² per 1000kcal),Land use per kilogram (m² per kilogram),Land use per 100g protein (m² per 100g protein),Scarcity-weighted water use per kilogram (liters per kilogram),Scarcity-weighted water use per 100g protein (liters per 100g protein),Scarcity-weighted water use per 1000kcal (liters per 1000 kilocalories),Category,Further processing needed
0,Wheat & Rye (Bread),0.1,0.0,0.8,0.2,0.1,0.1,0.1,1.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grains,yes
1,Maize (Meal),0.3,0.0,0.5,0.1,0.1,0.1,0.0,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grains,yes
2,Barley (Beer),0.0,0.0,0.2,0.1,0.0,0.5,0.3,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grains,yes
3,Oatmeal,0.0,0.0,1.4,0.0,0.1,0.1,0.0,1.6,4.281357,11.23,8.638462,183.911552,371.076923,482.4,0.945482,1.907692,2.897446,7.60,5.846154,18786.2,14450.923080,7162.104461,Grains,no
4,Rice,0.0,0.0,3.6,0.1,0.1,0.1,0.1,4.0,9.514379,35.07,49.394366,609.983722,3166.760563,2248.4,1.207271,6.267606,0.759631,2.80,3.943662,49576.3,69825.774650,13449.891480,Grains,yes
5,Potatoes,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,4.754098,3.48,20.470588,80.737705,347.647059,59.1,0.628415,2.705882,1.202186,0.88,5.176471,2754.2,16201.176470,3762.568306,Vegetables,yes
6,Cassava,0.6,0.0,0.2,0.0,0.1,0.0,0.0,0.9,0.708419,0.69,7.666667,NaN,NaN,0.0,1.355236,14.666667,1.858316,1.81,20.111111,0.0,NaN,NaN,Vegetables,yes
7,Cane Sugar,1.2,0.0,0.5,0.0,0.8,0.1,0.0,2.6,4.820513,16.92,NaN,176.666667,NaN,620.1,0.911681,NaN,0.581197,2.04,NaN,16438.6,NaN,4683.361823,Sugar,no
8,Beet Sugar,0.0,0.0,0.5,0.2,0.6,0.1,0.0,1.4,1.541311,5.41,NaN,62.022792,NaN,217.7,0.515670,NaN,0.521368,1.83,NaN,9493.3,NaN,2704.643875,Sugar,no
9,Other Pulses,0.0,0.0,1.1,0.0,0.1,0.4,0.0,1.6,5.008798,17.08,7.977581,NaN,203.503036,435.7,0.524927,0.836058,4.565982,15.57,7.272303,22477.4,10498.552080,NaN,Vegetables,yes
10,Peas,0.0,0.0,0.7,0.0,0.1,0.0,0.0,0.8,2.173410,7.52,3.384338,NaN,178.487849,396.6,0.283237,0.441044,2.156069,7.46,3.357336,27948.2,12577.947790,NaN,Vegetables,yes
11,Nuts,-2.1,0.0,2.1,0.0,0.1,0.1,0.0,0.2,3.113821,19.15,11.726883,672.162602,2531.414574,4133.8,0.069919,0.263319,2.107317,12.96,7.936314,229889.8,140777.587300,37380.455280,Nuts,no
12,Groundnuts,0.4,0.0,1.4,0.4,0.1,0.1,0.0,2.4,2.437931,14.14,5.401070,319.362069,707.524828,1852.3,0.556897,1.233766,1.570690,9.11,3.479756,61797.9,23605.003820,10654.810340,Nuts,no
13,Soymilk,0.2,0.0,0.1,0.2,0.1,0.1,0.3,1.0,NaN,1.06,NaN,NaN,NaN,27.8,NaN,NaN,NaN,0.66,NaN,955.6,NaN,NaN,Plant_Dairy,no
14,Tofu,1.0,0.0,0.5,0.8,0.2,0.2,0.3,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Plant_Dairy,no
15,Soybean Oil,3.1,0.0,1.5,0.3,0.3,0.8,0.0,6.0,NaN,11.69,NaN,NaN,NaN,414.6,NaN,NaN,NaN,10.52,NaN,14888.2,NaN,NaN,Oils,no
16,Palm Oil,3.1,0.0,2.1,1.3,0.2,0.9,0.0,7.6,1.207014,10.67,NaN,0.723982,NaN,6.4,0.828054,NaN,0.273756,2.42,NaN,36.2,NaN,4.095023,Oils,no
17,Sunflower Oil,0.1,0.0,2.1,0.2,0.2,0.9,0.0,3.5,5.730769,50.66,NaN,114.015837,NaN,1007.9,0.407240,NaN,1.997738,17.66,NaN,36369.4,NaN,4114.185520,Oils,no
18,Rapeseed Oil,0.2,0.0,2.3,0.2,0.2,0.8,0.0,3.7,2.170814,19.19,NaN,26.889140,NaN,237.7,0.426471,NaN,1.202489,10.63,NaN,10593.7,NaN,1198.382353,Oils,no
19,Olive Oil,-0.4,0.0,4.3,0.7,0.5,0.9,0.0,6.0,4.214932,37.26,NaN,242.285068,NaN,2141.8,0.613122,NaN,2.976244,26.31,NaN,177480.2,NaN,20076.945700,Oils,no
20,Tomatoes,0.4,0.0,0.7,0.0,0.2,0.1,0.0,1.4,39.526316,7.51,68.272727,1946.315789,3361.818182,369.8,11.000000,19.000000,4.210526,0.80,7.272727,5335.7,48506.363640,28082.631580,Vegetables,no
21,Onions & Leeks,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,8.756757,3.24,24.923077,38.648649,110.000000,14.3,1.351351,3.846154,1.054054,0.39,3.000000,932.0,7169.230769,2518.918919,Vegetables,no
22,Root Vegetables,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,4.351351,1.61,16.100000,76.756757,284.000000,28.4,1.162162,4.300000,0.891892,0.33,3.300000,929.2,9292.000000,2511.351351,Vegetables,no
23,Brassicas,0.0,0.0,0.3,0.0,0.1,0.0,0.0,0.4,29.470588,5.01,45.545455,702.352941,1085.454545,119.4,3.000000,4.636364,3.235294,0.55,5.000000,8455.1,76864.545450,49735.882350,Vegetables,no
24,Other Vegetables,0.0,0.0,0.2,0.1,0.2,0.0,0.0,0.5,NaN,2.27,NaN,NaN,NaN,102.5,NaN,NaN,NaN,0.38,NaN,4911.4,NaN,NaN,Vegetables,no
25,Citrus Fruit,-0.1,0.0,0.3,0.0,0.1,0.0,0.0,0.3,7.000000,2.24,37.333333,258.437500,1378.333333,82.7,1.218750,6.500000,2.687500,0.86,14.333333,4662.7,77711.666670,14570.937500,Fruits,no
26,Bananas,0.0,0.0,0.3,0.1,0.3,0.1,0.0,0.8,5.483333,3.29,36.555556,190.833333,1272.222222,114.5,1.433333,9.555556,3.216667,1.93,21.444444,661.9,7354.444444,1103.166667,Fruits,no
27,Apples,0.0,0.0,0.2,0.0,0.1,0.0,0.0,0.3,3.020833,1.45,48.333333,375.208333,6003.333333,180.1,0.895833,14.333333,1.312500,0.63,21.000000,12948.6,431620.000000,26976.250000,Fruits,no
28,Berries & Grapes,0.0,0.0,0.7,0.0,0.2,0.2,0.0,1.1,10.736842,6.12,61.200000,736.140351,4196.000000,419.6,2.684211,15.300000,4.228070,2.41,24.100000,21162.1,211621.000000,37126.491230,Fruits,no
29,Wine,-0.1,0.0,0.6,0.1,0.1,0.7,0.0,1.4,NaN,4.57,NaN,NaN,NaN,78.9,NaN,NaN,NaN,1.78,NaN,1149.3,NaN,NaN,Other,no
30,Other Fruit,0.1,0.0,0.4,0.0,0.2,0.0,0.0,0.7,NaN,2.43,NaN,NaN,NaN,153.5,NaN,NaN,NaN,0.89,NaN,9533.1,NaN,NaN,Fruits,no
31,Coffee,3.7,0.0,10.4,0.6,0.1,1.6,0.1,16.5,197.357143,110.52,138.150000,46.250000,32.375000,25.9,50.946429,35.662500,38.607143,21.62,27.025000,337.0,421.250000,601.785714,Other,yes
32,Dark Chocolate,14.3,0.0,3.7,0.2,0.1,0.4,0.0,18.7,16.843327,87.08,174.160000,104.564797,1081.200000,540.6,9.023211,93.300000,13.338491,68.96,137.920000,2879.2,5758.400000,556.905222,Other,no
33,Beef (beef herd),16.3,1.9,39.4,1.3,0.3,0.2,0.2,59.6,110.406593,301.41,151.158475,531.575092,727.783350,1451.2,36.439560,49.889669,119.490842,326.21,163.595787,34732.5,17418.505520,12722.527470,Animal_Prod,yes
34,Beef (dairy herd),0.9,2.5,15.7,1.1,0.4,0.3,0.2,21.1,133.805861,365.29,185.050659,994.249084,1375.025329,2714.3,12.197802,16.869301,15.838828,43.24,21.904762,119805.2,60691.590680,43884.688640,Animal_Prod,yes
35,Lamb & Mutton,0.5,2.4,19.5,1.1,0.5,0.3,0.2,24.5,30.640379,97.13,48.540730,568.706625,900.949525,1802.8,12.529968,19.850075,116.659306,369.81,184.812594,141925.0,70927.036480,44771.293380,Animal_Prod,yes
36,Pig Meat,1.5,2.9,1.7,0.3,0.3,0.3,0.2,7.2,31.958159,76.38,47.206428,751.380753,1109.888752,1795.8,5.150628,7.608158,7.263598,17.36,10.729295,66867.4,41327.194070,27977.991630,Animal_Prod,yes
37,Poultry Meat,2.5,1.8,0.7,0.4,0.3,0.2,0.2,6.1,26.324324,48.70,28.117783,356.756757,381.062356,660.0,5.335135,5.698614,6.605405,12.22,7.055427,14177.9,8185.854503,7663.729730,Animal_Prod,yes
38,Milk,0.5,0.2,1.5,0.1,0.1,0.1,0.3,2.8,17.750000,10.65,32.272727,1047.000000,1903.636364,628.2,5.250000,9.500000,14.916667,8.95,27.121212,19786.3,59958.484850,32977.166670,Dairy,no
39,Cheese,4.5,2.3,13.1,0.7,0.1,0.2,0.3,21.2,25.418605,98.37,44.551630,1448.372093,2538.586957,5605.2,6.170543,10.815217,22.684755,87.79,39.759964,180850.6,81906.974640,46731.421190,Dairy,no
40,Eggs,0.7,2.2,1.3,0.0,0.1,0.2,0.0,4.5,15.111111,21.76,19.610671,401.180556,520.638068,577.7,3.243056,4.208724,4.354167,6.27,5.650685,17982.7,16206.470800,12487.986110,Egg_Prod,yes
41,Fish (farmed),0.5,0.8,3.6,0.0,0.1,0.1,0.0,5.1,131.351955,235.12,103.100197,2062.178771,1618.636264,3691.3,7.614525,5.976759,4.698324,8.41,3.687788,41572.2,18229.423370,23224.692740,Animal_Prod,yes
42,Shrimps (farmed),0.2,2.5,8.4,0.0,0.2,0.3,0.2,11.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Animal_Prod,yes

In [13]:
# Speichern des verarbeiten DF für die Streamlit Anwendung:
# df_food.to_csv('df_food.csv')

In [14]:
df_food.to_excel('df_food.xlsx')

### Visualisierungen

In [ ]:
df = df_food
fig = px.scatter(df, size="Total_emissions", y="Land use per kilogram (m² per kilogram)",
                 x = 'Freshwater withdrawals per kilogram (liters per kilogram)', color="Category",
           hover_name="Food product", size_max=60,
                color_discrete_sequence=px.colors.qualitative.Prism)
fig.show()

Zum Einstieg wurde eine interaktive Graphik mit plotly express erstell. Die Graphik kann viele Aspekte auf einmal darstellen. Es werden 3 metrische Merkmale (Wasserverbrauch, Landverbrauch, Gesamtemissionen dargestellt. Es können verschiedene Kategorien einzeln gewählt werden. Interaktiv auf einer Website eignen sich die Graphik ganz gut, aber als statisches Bild wäre sie nicht geeignet. Dafür werden die folgenden Graphiken zu bestimmten Fragestellungen entwickelt.

#### Frage 1:
Welches ist das nachhaltigste Lebensmittel (geringste Gesamtemissionen) für die gewählte Kategorie?

In [ ]:
categories = df_food["Category"].unique()
categories

In [ ]:
plt.figure(figsize=(20, 10))
cats = ['Dairy', 'Plant_Dairy', 'Animal_Prod', 'Egg_Prod']
filtered = df_food[df_food['Category'].isin(cats)]
sns.barplot(x = filtered['Food product'], y = filtered['Total_emissions'], palette="rocket")
plt.title(f'Total Emissions per kg of Food for Different Foods in the Chosen Categories = {cats}',
          fontsize=18, color= 'black', fontweight='bold')
plt.xlabel('')
plt.xticks(fontsize=10)
plt.yticks(fontsize=15)
plt.ylabel('Total Emissions', fontsize=18)
sns.despine(left=True, bottom=True)

#### Design Entscheidungen für Frage 1:
Die Achsen werden zum Decluttering entfernt, nur die Beschriftung wird zu einfacheren Einordnung beibehalten. Zur Information über die Gewählten Kategorien werden diese im Titel angegeben. Ein leichter Farbverlauf ist zur ästhestischen Wahrnehmung gewählt. Die Farbpalette ist in Rot-Violett-Tönen gehalten, um die negative Auswirkung der Emissionen zu unterstreichen. Aufgrund der wählbaren Kategorien ist es schwierig, die Farben und die Größe der x-Achsen-Beschriftung zur stärkeren Hervorhebung zu wählen. Die Größe der x-Achsen-Beschriftung wurde daher eher kleiner gewählt, um Überlappung zu vermeiden. Als automatisch 'Preattentive' kann schon die Höhe der Balken gelten, wobei die Aufmerksamkeit auf die größten Balken gelenkt wird.
Zur allgemeinen ästhetischen Gestaltung werden einfache Formen mit angenehmem Abstand gewählt. Die Balken eignen sich gut, um die absolute Größe der Emissionen auszudrücken. Es werden keine Linien eingezeichnet, da die genaue Zahl der Gesamtemissionen nicht im Vordergrund steht, sondern der Vergleich.
Die Beschriftung der y-Achse könnte zwar rotiert werden, passt dann aber nicht mehr in den gedachten Linienverlauf.

#### Frage 2:
Welcher Lebenszyklusschritt hat den größten Einfluss auf die Gesamtemissionen (für gewählte Lebensmittel)?

In [ ]:
stages = ['Land use change', 'Animal Feed', 'Farm', 'Processing',
           'Transport', 'Packging', 'Retail']

In [ ]:
lifecycle = df_food[['Food product','Land use change', 'Animal Feed', 'Farm', 'Processing',
           'Transport', 'Packging', 'Retail']]
lifecycle = lifecycle.T
lifecycle.columns = lifecycle.loc['Food product']
lifecycle.drop('Food product', axis = 0, inplace=True)

In [ ]:
lifecycle['stage'] = stages

In [ ]:
plt.figure(figsize=(20, 10))
plt.title(f'Total Emissions per Processing Stage of Different Foods',
          fontsize=18, color= 'black', fontweight='bold')

choice = ['Potatoes', 'Cassava', 'Cane Sugar', 'Maize (Meal)', 'Root Vegetables']
sns.lineplot(lifecycle[choice], dashes= True, legend='full', linewidth = 5, alpha = 0.6)
plt.xticks(fontsize=15)
plt.yticks(fontsize=15)
plt.legend(fontsize=15)
sns.despine(left=True, bottom=True)

#### Design Entscheidungen für Frage 2:
Die Achsen werden zum Decluttering entfernt, nur die Beschriftung wird zu einfacheren Einordnung beibehalten. Zur Information über die Gewählten Lebensmittel wird die Legende groß eingeblendet. Der Plot ist durch den Titel und die Achsenbeschriftungen trotzdem begrenzt.
Es wird ein Liniendiagram verwendet, um den Verlauf des Lebenszyklus zu zeigen. Es werden keine Grid-Linien eingezeichnet, da die genaue Zahl der Gesamtemissionen nicht im Vordergrund steht, sondern der Vergleich. Die Farben werden bei default belassen, da sich die Farben so deutlich unterscheiden, was eine bessere Erkennung gewährleistet. Obwohl die gestrichelten Linien nicht sehr ästhetisch wirken, werden sie hier eingesetzt, um eventuell überlappende Bereiche besser darstellen zu können. Das Gestalt-Prinzip 'Similarity' wird hier angewandt.Die Linien sind leicht durchsichtig, ebenfalls wegen überlappender Linien.
Als automatisch 'Preattentive' kann schon die Bewegung der Balken gelten, wobei die Aufmerksamkeit auf die größten Balken gelenkt wird. Es wird versucht, die Aufmerksamkeit mit den Farben NICHT speziell zu lenken, da der Plot interaktiv ist und daher die Aussage verändert werden kann.

#### Frage 3:
Was ist das am wenigsten effiziente Lebensmittel in Bezug auf Treibhausgasemissionen pro 100 g Protein (kg CO₂eq pro 100 g Protein)?

In [ ]:
plt.figure(figsize=(20, 10))
cats =  ['Dairy', 'Plant_Dairy', 'Animal_Prod', 'Egg_Prod']
filtered = df_food[df_food['Category'].isin(cats)]
sns.barplot(x = filtered['Food product'],
            y = filtered['Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)'],
           palette="rocket")
plt.title(f'Greenhouse Gas Emissions per 100g PROTEIN in the Chosen Categories = {cats}', 
                   fontsize=18, color= 'black', fontweight='bold')
plt.xlabel('')
plt.xticks(fontsize=10)
plt.yticks(fontsize=15)
plt.ylabel('Greenhouse gas emissions per 100g protein (kgCO₂eq per 100g protein)', fontsize=13.5)
sns.despine(left=True, bottom=True)

#### Design Entscheidungen für Frage 3:
Die Achsen werden zum Decluttering entfernt, nur die Beschriftung wird zu einfacheren Einordnung beibehalten. Die  Der Plot ist durch den Titel und die Achsenbeschriftungen trotzdem begrenzt. Zur Information über die Gewählten Kategorien werden diese im Titel angezeigt. Der Fokus liegt hier auf der Einheit für 100g Protein, daher ist diese Information im Titel in Großbuchstaben angegeben.
Zur allgemeinen ästhetischen Gestaltung werden einfache Formen mit angenehmem Abstand gewählt. Es wird wiederum ein Balkendigram gewählt. Die Balken eignen sich gut, um die absolute Größe der Emissionen auszudrücken. Es werden keine Linien eingezeichnet, da die genaue Zahl der Gesamtemissionen nicht im Vordergrund steht, sondern der Vergleich. Die Darstellungen sollen für eine Website oder sogar eine einzige Seite designt werden. Um die Darstellungen konsistent zu halten, ist die Darstellung an der Darstellung für Frage 1 angelehnt.
Als automatisch 'Preattentive' kann wiederum die Höhe der Balken gelten, wobei die Aufmerksamkeit auf die größten Balken gelenkt wird. Je nach Auswahl der Kategorien sind auch jene Lebensmittel auffällig, bei denen kein Balken angezeigt wird. Diese haben besonders geringe Emissionen und sollten auch auffallen.

#### Frage 4:
Was ist das am wenigsten effiziente Lebensmittel in Bezug auf Treibhausgasemissionen pro 1000kcal (kgCO₂eq per 1000kcal)? Hier wird also nur der Nährwert des Lebensmittels berücksichtigt!

In [ ]:
plt.figure(figsize=(20, 10))
cats = ['Dairy', 'Plant_Dairy', 'Oils', 'Sugar']
filtered = df_food[df_food['Category'].isin(cats)]
sns.barplot(x = filtered['Food product'], y = filtered['Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)'],
           palette="rocket")
plt.title(f'Greenhouse Gas Emissions per 1000kcal (CALORIFIC VALUE) in the Chosen Categories = {cats}',
                   fontsize=18, color= 'black', fontweight='bold')
plt.xlabel('')
plt.xticks(fontsize=10)
plt.yticks(fontsize=15)
plt.ylabel('Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)', fontsize=13.5)
sns.despine(left=True, bottom=True)

#### Design Entscheidungen für Frage 4:
Diese Darstellung ist sehr ähnlich zu Darstellung Nummer 3. Die meisten Designentscheidungen sind gleich, das Design soll konsistent gehalten werden. Der Unterschied zu Frage 3, worin es um den Protein/Eiweißgehalt des Lebensmittels geht, soll im Titel hervorgehoben werden. Eine Möglichkeit um noch mehr Information einzubringen, wäre das Annotieren (direkt über den Balken) der jeweiligen Proteingehalte in Darstellung 3 oder der Brennwerte hier in Darstellung 4. Die Informationen sind im aktuellen Datensatz nicht verfügbar. Der zusätzliche Text könnte außerdem die Darstellunge etwas überladen.

#### Frage 5:
Wie korrelieren Nachhaltigkeitsmaße und Emissionen?

In [ ]:
per_protein = df_food.columns[[11, 13, 16, 19, 21]]
per_calories = df_food.columns[[9, 12, 15, 17, 22]]
measures = df_food[per_calories]
mask = np.triu(np.ones_like(measures.corr(), dtype=bool))
plt.figure()
ax = sns.heatmap(measures.corr(), cmap="mako",
            annot= True, center=0.8,
           square=True, linewidths=.5,
           mask=mask)
ax.xaxis.tick_top()
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
ax.set_xticklabels(['Eutrophying Em', 'Freshwater Withd', 'Greenhouse gem', 'Land use', 'Scarcity water' ], rotation=90)
sns.despine(left=True, bottom=True)
plt.title('Pearson - Correlations', loc = 'right', y= 0.8)

#### Design Entscheidungen für Frage 5:
Um Korrelationen festzustellen, wird eine Heatmap erstellt. Dabei werden ruhige Farben (Blautöne) gewählt. Korrelationen sind weder gut noch schlecht, nur die Helligkeit soll die Stärke der Korrelationen anzeigen. Unnötige Bereiche wie Begrenzungen oder die zweite Hälfte der Matrix werden für die bessere Übersichtlichkeit entfernt. Das Korrelationmaß wird im Gegensatz zum eben erwähnten Decluttering angegeben, um die Farben genauer deuten zu können. Die Farben sollen das Auge nur lenken. Auf der y-Achse ist die gesamte Beschreibung der Nachhaltigkeitsmaße angegeben, damit der Betrachter weiß, worum es sich genau handelt. Die Angaben können gekürzt werden, wie auf der x-Achse dargestellt. Aufgrund der Länge der Beschriftungen können diese nur vertikal dargestellt werden. Um das Lesen trotzdem zu erleichtern, wird der Text abgekürzt dargestellt. Vorraussetzung für das richtige Lesen des Plots ist nun, dass der Leser weiß, dass es sich bei der x-Achse um die gleichen Maße wie in der y-Achse handelt. Als Hinweis dazu dient der Titel 'Pearson-Correlations', der in den Plot verschoben wurde, um die aktuelle rechteckige Form beibehalten zu können.

#### Frage 6:
Verursachen Lebensmittel, die keiner weiteren Verarbeitung bedürfen, während der vorhergehenden Verarbeitungsschritte höhere Emissionen?

In [ ]:
plt.figure(figsize=(20, 20))
# filtered = df_food[df_food['Category']=='Animal_Prod']
sns.barplot(y = df_food['Food product'], x = df_food['Total_emissions'], hue = df_food['Further processing needed'],
          palette='magma', orient = 'h', width=0.8, dodge=False, hue_order= ['yes', 'no'] )
#px.bar(x = df_food['Food product'], y = df_food['Total_emissions'], color= df_food['Further processing needed'])
plt.title('Total_emissions per kg of food for differnt foods in the chosen category',
                            fontsize=18, color= 'black', fontweight='bold')

plt.ylabel('')
plt.xticks(fontsize=13)
plt.yticks(fontsize=13)
plt.xlabel('Greenhouse gas emissions per 1000kcal (kgCO₂eq per 1000kcal)', fontsize=15)
plt.legend(fontsize=15)
sns.despine(left=True, bottom=True)

#### Design Entscheidungen für Frage 6:
Diese Darstellung ist sehr ähnlich zu Darstellung Nummer 3 und 4. Die meisten Designentscheidungen sind gleich, das Design soll konsistent gehalten werden. Mehrere Farbpalette stehen zur Auswahl, aber das Design soll einerseits konisitenz gehalten werden, andererseits sollen die Farben gut voneinander zu unterscheiden sein. Starke Farben wie primärfarben (zB rot und grün in einem Plot) ind nicht sehr ästhetisch und wirken sehr intensiv. Die Farben in diesem Plot sollen besonders den Unterschied der beiden Kategorien (Weiterverarbeitung ja/nein) hervorheben. Die Farben sollen keinenfalls positives ausdrücken, da es immer noch um Emissionen geht. Daher sind die Farben wie schon vorher eher dunkel bis rötlich gewählt.
Aufgrund der langen Titel ist der Barplot horizontal ausgerichtet. Die Namen der Lebensmittelprodukte sollen gut lesbar sein. Der Parameter dodge=False, damit pro Lebensmittel nur ein Balken mit einer Kategorie angezeigt wird. Der Namer der y-Achse (ylabel) ist entfernt, da auch so erkennbar ist, dass es sich um Lebensmittel handelt. Es sollen zum Vergleich alle Lebensmittel dargestellt werden, daher gibt es keine Option zum Filtern.

#### Ergänzung zur Entwicklung mit Streamlit:
Für die Entwicklung in Streamlit wurden Select-Tools für die Kategorien gegeben. Es kann somit mit dem Plot interagiert werden. Zur besseren Erkennung der Kategorien wurde der Farberlauf für Plots 1, 3 und 4 gelöscht und die Kategorien mit Farbe gekennzeichnet.

Um mehr interaktive Plots einzubringen, wurde der letzte Plot mit plotly express gestaltet. Der Übersichtsplot mit Plotly zu Beginn wurde ebenfalls in die Streamlit-App übernommen. Die Farbskala wurde ähnlich zu den anderen Plots gewählt. Designentscheidungen bleiben weitgehendst erhalten.

In [ ]:
fig2 = px.bar(data_frame =df_food,  y = 'Food product', x = 'Total_emissions', color= 'Further processing needed',
        color_discrete_sequence=px.colors.qualitative.Prism, width=1000, height= 800 )
fig2.show()